pipeline:
  docker-build:
    image: plugins/docker
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    repo: docker.studynator.me/bzone/bztools
    registry: docker.studynator.me
    dockerfile: Dockerfile.bztools
    tags: 
      - latest
      - ${DRONE_TAG}
    when:
      event:
        - tag
