pipeline:
  docker-build:
    image: plugins/docker
    repo: docker.studynator.me/bzone/bztools
    registry: docker.studynator.me
    dockerfile: Dockerfile.bztools
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    debug: true
    tags: 
      - latest
      - ${DRONE_TAG}
    when:
      event:
        - tag
