pipeline:
  docker-build:
    image: plugins/docker
    repo: thejanne/bztools
    dockerfile: Dockerfile
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    tags: 
      - latest
      - ${DRONE_TAG}
    when:
      event:
        - tag
