pipeline:
  docker-build:
    image: plugins/docker
    dockerfile: Dockerfile
    settings:
      repo: thejanne/bztools
      username: thejanne
      password:
        from_secret: docker_password
      tags: 
        - latest
        - ${DRONE_TAG}
    when:
      event:
        - tag
