kind: pipeline
name: default

steps:
- name: docker-build
  image: plugins/docker
  settings:
    repo: thejanne/bztools
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auth:
      from_secret: docker_password
    tags: 
      - latest
      - ${DRONE_TAG}
  trigger:
    branch:
    - master
    event:
    - tag
